### obtener equipos
GET http://localhost:3000/api/equipos


### obtener un equipo
GET http://localhost:3000/api/equipos/1

### crear equipo  
POST http://localhost:3000/api/equipos
Content-Type:application/json

{  
    "nombre": "Union",
    "liga": "LPF",
    "pais": "Argentina",
    "categoria": "Primera A"
}

### modificar un equipo
PUT http://localhost:3000/api/equipos/2
Content-Type:application/json

{  
    "nombre": "Central",
    "liga": "LPF",
    "pais": "Argentina",
    "categoria": "Primera A"
}
#### modificar
PATCH  http://localhost:3000/api/equipos/2
Content-Type:application/json

{  
    "nombre": "Sarmiento",
    "categoria": "Primera A"
}

### eliminar equipo
DELETE http://localhost:3000/api/equipos/2
