### obtener equipos
GET http://localhost:3000/api/jugadores


### obtener un equipo
GET http://localhost:3000/api/jugadores/2

### crear equipo  
POST http://localhost:3000/api/jugadores
Content-Type:application/json

{  
    "nombre": "borja",
    "apellido": "Lo Celso",
    "dni":"40840234",
    "edad": "29",
    "numero":"20",
    "posicion":"dc",
    "dts": 4,
    "estadisticas": 2025
}

### modificar un equipo
PUT http://localhost:3000/api/jugadores/3
Content-Type:application/json

{  
    "nombre": "Lionel",
    "apellido": "Messi",
    "numero": "10",
    "edad": "36",
    "dni":"46834644",
    "posicion":"mco"

}
#### modificar
PATCH  http://localhost:3000/api/jugadores/3
Content-Type:application/json

{  
    "nombre": "Cristiano",
    "apellido": "Ronaldo"
}

### eliminar equipo
DELETE http://localhost:3000/api/jugadores/3