### obtener lesiones
GET http://localhost:3000/api/lesiones


### obtener un lesion
GET http://localhost:3000/api/lesiones/1

### crear lesion  
POST http://localhost:3000/api/lesiones
Content-Type:application/json

{ 
    "cdLesion": "A",
    "descLesion": "Desgarro en partido",
    "jugador": 2,
    "tipoLesion":5
}

### modificar una lesion
PUT http://localhost:3000/api/lesiones/2
Content-Type:application/json

{  
    "cdLesion": "C",
    "descLesion": "Fractura en choque"
}
#### modificar
PATCH  http://localhost:3000/api/lesiones/2
Content-Type:application/json

{  
    "cdLesion": "B" 
}

### eliminar lesion
DELETE http://localhost:3000/api/lesiones/2
