### obtener lesiones
GET http://localhost:3000/api/lesiones


### obtener un lesion
GET http://localhost:3000/api/lesiones/4

### crear lesion  
POST http://localhost:3000/api/lesiones
Content-Type:application/json

{ 
    "cdLesion": "B",
    "descLesion": "Desgarro en partido",
    "jugador": 1,
    "tipoLesion":5
}

### modificar una lesion
PUT http://localhost:3000/api/lesiones/6
Content-Type:application/json

{  
    "cdLesion": "C",
    "descLesion": "Fractura en choque",
    "jugador": 1,
    "tipoLesion":7
}
#### modificar
PATCH  http://localhost:3000/api/lesiones/6
Content-Type:application/json

{  
    "cdLesion": "B" 
}

### eliminar lesion
DELETE http://localhost:3000/api/lesiones/4
