### obtener tipo lesiones
GET http://localhost:3000/api/tipoLesiones




### Crear tipo de lesión
### @name createTipoLesiones
POST http://localhost:3000/api/tipoLesiones
Content-Type: application/json

{
    "cdTipoLesion": "DESG015",
    "descTipoLesion": "Desgarro",
    "diasRecuperacion": "25",
    "tratamiento": "magneto"
}

### ID
//@id = {{createTipoLesiones.response.body.data.id}}

### Obtener tipo de lesión por id
GET http://localhost:3000/api/tipoLesiones/1


### put
PUT http://localhost:3000/api/tipoLesiones/1
Content-Type:application/json

{  
    "descTipoLesion": "Fractura",
    "diasRecuperacion": "65",
    "tratamiento": "Yeso, reposo, kinesiologia"
}
#### modificar
PATCH  http://localhost:3000/api/tipoLesiones/1
Content-Type:application/json

{  
    "descTipoLesion": "Esguince",
    "diasRecuperacion": "10"
}

### eliminar tipo lesion
DELETE http://localhost:3000/api/tipoLesiones/4
