### obtener equipos
GET http://localhost:3000/api/personas


### obtener un equipo
GET http://localhost:3000/api/personas/a02b91bc-3769-4221-beb1-d7a3aeba7dad


### crear equipo  
POST http://localhost:3000/api/personas
Content-Type:application/json

{  
    "tipo": "Jugador",
    "nombre": "LPF",
    "apellido": "Argentina",
    "edad": "Primera A",
    "id":""
}

### modificar un equipo
PUT http://localhost:3000/api/equipos/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type:application/json

{  
    "nombre": "Central",
    "liga": "LPF",
    "pais": "Argentina",
    "categoria": "Primera A"
}
#### modificar
PATCH  http://localhost:3000/api/equipos/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type:application/json

{  
    "nombre": "river",
    "categoria": "Primera A"
}

### eliminar equipo
DELETE http://localhost:3000/api/equipos/a02b91bc-3769-4221-beb1-d7a3aeba7dad