### obtener partidos
GET http://localhost:3000/api/partido


### obtener un partido
GET http://localhost:3000/api/partido/1


### crear partido
POST http://localhost:3000/api/partido
Content-Type:application/json

{  
    "fecha": "16/05/2025",
    "tipo": "Copa Argentina",
    "horario": "15:30",
    "lugar": "Cordoba",
    "rival": "River Plate",
    "nroFecha": "3",
    "equipo": "3"
}

### modificar un partido
PUT http://localhost:3000/api/partido/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type:application/json

{  
    "fecha": "16/05/2026",
    "tipo": "liga",
    "horario": "15:30",
    "lugar": "Cordoba",
    "rival": "Instituto",
    "nroFecha": "20",
}
#### modificar
PATCH  http://localhost:3000/api/partido/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type:application/json

{  
    "tipo": "amistoso",
    "rival": "Quiaca",
}

### eliminar partido
DELETE http://localhost:3000/api/partido/a02b91bc-3769-4221-beb1-d7a3aeba7dad